%% RUN_EXAMPLE
% End-to-end walkthrough using synthetic data. The example demonstrates the
% streamlined default output plus the optional condensed boundary comparison.

%% Locate the repository and example folders
example_dir = string(fileparts(mfilename("fullpath")));
repo_dir = string(fileparts(fileparts(example_dir)));
input_dir = fullfile(example_dir, "inputs");
output_dir = fullfile(example_dir, "output");
addpath(repo_dir, example_dir);

%% Run the pipeline
fprintf("\n=== Running pipeline ===\n");
run_detrital_pipeline(input_dir, output_dir, ...
    Kmax=5, ...
    NSigma=1.0, ...
    P_thresh=0.65, ...
    Delta=8, ...
    run_sensitivity=true);

%% Inspect the run-level summaries
fprintf("\n=== Selected-component summary ===\n");
psum = readtable(fullfile(output_dir, "pipeline_summary.csv"), ...
    VariableNamingRule="preserve");
disp(psum(:, {'Catchment','target_component_mean_Ma', ...
    'target_component_sigma_Ma','candidate_model_start_Ma', ...
    'target_window_lo_Ma','target_window_hi_Ma'}));

fprintf("\n=== Reference-boundary sensitivity ===\n");
sens = readtable(fullfile(output_dir, "reference_boundary_sensitivity_summary.csv"), ...
    VariableNamingRule="preserve");
disp(sens(:, {'Catchment','Chronometer','PrimaryOlderBoundary_Ma', ...
    'ModelInputs_PrimaryOlderBoundary','YoungerBoundary_Ma', ...
    'ModelInputs_YoungerBoundary'}));

%% Inspect one catchment's one-date-per-row screening table
fprintf("\n=== First rows of CatchmentA filter results ===\n");
screening = readtable(fullfile(output_dir, "CatchmentA", ...
    "filter_output", "filter_results_full.csv"), ...
    VariableNamingRule="preserve");
disp(screening(1:min(10,height(screening)), ...
    {'GrainID','Chronometer','PairRole','Age_Ma','ReferenceCode', ...
     'ReviewCode','Action','ModelInclude'}));

fprintf("\nExample run complete.\n");
fprintf("Output folder: %s\n", output_dir);
fprintf("Start with: %s\n", fullfile(output_dir, "README.txt"));
fprintf("Full screening table: %s\n", fullfile(output_dir, "CatchmentA", ...
    "filter_output", "filter_results_full.csv"));
