function run_chapter1_configuration(inputRoot, outputRoot)
%RUN_CHAPTER1_CONFIGURATION Reproduce the Chapter 1 screening settings.
% WP uses a reviewed K=3 override. OP and TC retain automatic BIC selection.
% This file contains configuration only. Dissertation data are not included.

arguments
    inputRoot  (1,1) string
    outputRoot (1,1) string
end

K_map = containers.Map({'WP'}, {3});

run_detrital_pipeline(inputRoot, outputRoot, ...
    TargetComponentAgeRange=[70 300], ...
    Kmax=6, ...
    K_override_map=K_map, ...
    NSigma=1, ...
    P_thresh=0.65, ...
    Delta=8, ...
    run_sensitivity=true);
end
